config/routes.rb
Rails.application.routes.draw do
  resources :fencers

  resources :results

  controller :get_results do
    get 'update_database' => :update_database
    get 'get_results' => :get_results
    get 'get_round_results' => :get_round_results
    get 'get_lori' => :get_lori
  end

end

app/models/fencer.rb
class Fencer < ActiveRecord::Base
	has_many :results
	has_many :round_results, through: :results


	def average_place (results)
		puts results.size
		score = 0
		total = 0
		results.each do |result|
			score += result.place
			total += 1
		end

		if total == 0 then
			return "No Results"
		end

		return score/total
	end

	def non_complete_pools (rounds)
		total = 0
		non_completes = 0
		rounds.each do |round|
			if round.score < 5 && round.opponent_score < 5 then
				non_completes += 1
			end
			total += 1
		end
	end

	def non_complete_de (rounds)
		total = 0
		non_completes = 0
		rounds.each do |round|
			if round.score < 15 && round.opponent_score < 15 then
				non_completes += 1
			end
			total += 1
		end
	end

	def biggest_upset (rounds)
		biggest_win = 0
		biggest_loss = 0
		rounds.each do |round|
			opponent_seed = round.opponent_seed
			self_seed = round.seed
			if round.victory == "V" && opponent_seed > self_seed then
				biggest_win = [biggest_win, (opponent_seed - self_seed)].max 
			elsif round.victory == "D" && opponent_seed < self_seed then
				biggest_loss = [biggest_loss, (self_seed - opponent_seed)].max
			end
		end
	end

	def total_touches (rounds)
		total_scored = 0
		total_taken = 0
		rounds.each do |round|
			total_scored += round.score
			total_taken += round.opponent_score
		end
		return [total_scored, total_taken]
	end

	def nemesis_club (rounds)
		defeats = Hash.new
		rounds.each do |round|
			if round.victory == "D" then
				if defeats.has_key? round.opponent_club_id then
					defeats[round.opponent_club_id] += 1
				else
					defeats[round.opponent_club_id] = 0
				end
			end
		end
		defeats.sort_by! {|k, v| v}
		clubs = defeats.keys
		return clubs[0]
	end

	def favored_club
		victories = Hash.new
		rounds.each do |round|
			if round.victory == "V" then
				if victories.has_key? round.opponent_club_id then
					victories[round.opponent_club_id] += 1
				else
					victories[round.opponent_club_id] = 0
				end
			end
		victories.sort_by! {|k, v| v}
		clubs = victories.keys
		return clubs[0]
		end
	end

	def win_loss (rounds)
		victories = 0.00
		losses = 0.00
		rounds.each do |round|
			if round.victory == "V" then
				victories += 1.0
			else
				losses += 1.0
			end
		end

		return victories / (victories + losses) * 100
	end

end

app/controllers/fencers_controller.rb
class FencersController < ApplicationController
  before_action :set_fencer, only: [:show, :edit, :update, :destroy]

  # GET /fencers
  # GET /fencers.json
  def index
    @fencers = Fencer.all
  end

  # GET /fencers/1
  # GET /fencers/1.json
  def show
  end

  # GET /fencers/new
  def new
    @fencer = Fencer.new
  end

  # GET /fencers/1/edit
  def edit
  end

  # POST /fencers
  # POST /fencers.json
  def create
    @fencer = Fencer.new(fencer_params)

    respond_to do |format|
      if @fencer.save
        format.html { redirect_to @fencer, notice: 'Fencer was successfully created.' }
        format.json { render :show, status: :created, location: @fencer }
      else
        format.html { render :new }
        format.json { render json: @fencer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fencers/1
  # PATCH/PUT /fencers/1.json
  def update
    respond_to do |format|
      if @fencer.update(fencer_params)
        format.html { redirect_to @fencer, notice: 'Fencer was successfully updated.' }
        format.json { render :show, status: :ok, location: @fencer }
      else
        format.html { render :edit }
        format.json { render json: @fencer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fencers/1
  # DELETE /fencers/1.json
  def destroy
    @fencer.destroy
    respond_to do |format|
      format.html { redirect_to fencers_url, notice: 'Fencer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fencer
      @fencer = Fencer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fencer_params
      params[:fencer]
    end
end

app/helpers/fencers_helper.rb
module FencersHelper
end

app/views/fencers/_form.html.erb
<%= form_for(@fencer) do |f| %>
  <% if @fencer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fencer.errors.count, "error") %> prohibited this fencer from being saved:</h2>

      <ul>
      <% @fencer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fencers/edit.html.erb
<h1>Editing fencer</h1>

<%= render 'form' %>

<%= link_to 'Show', @fencer %> |
<%= link_to 'Back', fencers_path %>

app/views/fencers/index.html.erb
<h1>Olympia's Fencers</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fencers.each do |fencer| %>
      <tr>
        <h1><%= fencer.first_name %> Average Place <%= " #{fencer.average_place fencer.results}" %></h1>
        <% total_touches = fencer.total_touches fencer.round_results %>
        <% if "#{fencer.average_place fencer.results}" != "No Results" then %>
        <h2> Total Touches Given <%= " #{total_touches[0]}" %> Total Touches Taken <%= " #{total_touches[1]}" %> Win-Loss = <%= "#{fencer.win_loss fencer.round_results}%" %></h2>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/fencers/new.html.erb
<h1>New fencer</h1>

<%= render 'form' %>

<%= link_to 'Back', fencers_path %>

app/views/fencers/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_fencer_path(@fencer) %> |
<%= link_to 'Back', fencers_path %>